#项目端口配置
server:
  port: 8080

  #MySql数据源配置
spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/lp?characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
     username: root
     password: root

#日志环境名称
  profiles:
       active: dev
  #资源url
  resources:
    static-locations: classpath:/static/
    #JPA相关配置
    #项目启动生成数据库
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
    #json数据格式
  jackson:
    serialization:
      indent-output: true


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
#日志
  logging:
    config: classpath:logback-spring.xml
    level:
      root: info
      com.example.demo.*.mapper: debug




